### ISSUE TITLE
Download目录是否可以进行文件删除

### ISSUE THREAD

**Issue by P0164860** [guolindev/ScopedStorageDemo#2]
你好，郭老师，想咨询您个问题，在Android10以后，我们应该是不能再删除 Download目录下的文件了吧，测试发现：可以写入，可以判断文件是否存在，但是无法进行文件的删除了。

**Comment by guolindev** [comment]
这个我还没有试，但是根据我的理解，如果Download目录下的这个文件是你创建的，那么你就可以对它进行删除，如果不是你创建的，那么肯定就无法删除了。我认为应该是这样。

**Comment by P0164860** [comment]
试了呢，郭老师，在Download目录下，我以项目包名创建了图片文件，能判断出图片文件是存在的，然后使用val delete = mFileDownload.delete() 方法，总是删除失败！

**Comment by guolindev** [comment]
你不要用文件的方式去删除，用ContentResolver的delete方法，然后传图片的Uri路径的方式去删除，file.delete()肯定是不行的。

**Comment by P0164860** [comment]
感谢郭老师的回答，但是我只知道图片的绝对路径，不知道如何再去获取图片的Uri路径呢？希望郭老师再给指点一下。

**Comment by guolindev** [comment]
咦？那你是怎么向Download目录添加文件的，你添加文件用的Uri，就用同样的Uri去删除呀。

**Comment by guolindev** [comment]
我在这个demo项目里面应该就有演示，另外也可以参考这篇文章 https://guolin.blog.csdn.net/article/details/105419420

**Comment by dacaoyuan** [comment]
问题解决了，感谢，郭老师的指点。

**Comment by guolindev** [comment]
好的，那我就关闭了。
