### ISSUE TITLE
调用BitmapFactory.decodeStream读取外部uri的bitmap 返回空 ,再次获取stream才有值

### ISSUE THREAD

**Issue by DaneChen** [guolindev/ScopedStorageDemo#3]
郭神，最近适配老项目遇到一个问题，调用BitmapFactory.decodeStream读取外部uri的bitmap 返回空 ，只有当stream再读取一次才能返回结果，代码大概如下：

        final Options options = new Options();
        options.inJustDecodeBounds = true;
        InputStream inputStream = context.getContentResolver().openInputStream(pathUri);
        BitmapFactory.decodeStream(inputStream, null, options);
       options.inSampleSize = calculateInSampleSize(options, rqsW, rqsH);
       options.inJustDecodeBounds = false;
         //如果不再次获取stream，会返回空
       // inputStream = context.getContentResolver().openInputStream(pathUri);
        return BitmapFactory.decodeStream(inputStream, null, options);

第一次decodeStream计算大小是正常的，第二次decodeStream如果不重新获取一个inputStream 就会返回空
您有没有遇到这个问题呢？

**Comment by guolindev** [comment]
我猜测是因为你的stream在第一次测大小的时候被消费掉了，所以第二次去decode，流已经没了，就解析为空了。

我印象中流是有mark和reset用法的，你可以在测大小之前先mark一下，测完大小之后reset一下流，这样就不会被消费掉了。

**Comment by DaneChen** [comment]
确实是被消费掉了。试了下mark/reset方案，这个inputstream不支持。
context.getContentResolver().openInputStream 返回的是 ParcelFileDescriptor 的内部类AutoCloseInputStream，继承自FileInputStream，没有覆写markSupported、mark和reset方法，默认不支持mark/reset
InputStream子类中支持mark/reset的常见的有BufferedInputStream、ByteArrayInputStream等

所以，我还是老实地重新读取一个inputstream
感谢郭神这么迅速地回复！

**Comment by guolindev** [comment]
话说你这个问题和这个库没啥关系吧，那我就把这个问题关闭了。

**Comment by DaneChen** [comment]
哈哈，确实没啥关系。不过也是这次适配才会使用uri去加载Bitmap, 以前都是直接用路径。
